version: 2
updates:
- package-ecosystem: gradle
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  target-branch: main
  ignore:
  - dependency-name: org.flywaydb:flyway-core
    versions:
    - 7.5.2
    - 7.5.3
    - 7.5.4
    - 7.6.0
    - 7.7.0
    - 7.7.1
    - 7.7.2
    - 7.7.3
    - 7.8.0
    - 7.8.1
  - dependency-name: org.mariadb.jdbc:mariadb-java-client
    versions:
    - 2.7.1
