version: '3'

services:
  uaa:
    image: pcfseceng/uaa:latest
    ports:
      - 8080:8080
    volumes:
      - ./config/uaa.yml:/uaa/uaa.yml
  db:
    image: postgres
    ports:
    - 6543:5432
    environment:
      POSTGRES_DB: credhub
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
  credhub:
    build: .
    image: credhub/credhub:local
    volumes:
    - ./docker/config/:/etc/config/
    - .:/src
    depends_on: [db, uaa]
    links:
      - db
      - uaa
    ports:
    - 9000:9000
    environment:
      CREDHUB_AUTH_SERVER_EXTERNAL_URL: http://localhost:8080/uaa/
      CREDHUB_AUTH_SERVER_INTERNAL_URL: http://uaa:8080/uaa/
      #https://35.196.32.64:8443
      TRUST_STORE_PASSWORD: changeit
      LOG_LEVEL: debug
      DATABASE: postgres
      DATABASE_USERNAME: admin
      DATABASE_PASSWORD: admin
      DATABASE_URL: jdbc:postgresql://db:5432/credhub?autoReconnect=true
