security:
  authorization:
    acls:
      enabled: true
    permissions:
    - actors:
        - "uaa-client:credhub_client"
      operations:
        - read
        - write
        - delete
        - read_acl
        - write_acl
      path: "/*"
  oauth2:
    resource:
      id: credhub
    enabled: true
