spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/credhub_dev?serverTimezone=UTC
  profiles:
    include: dev
  flyway:
    locations: classpath:/db/migration/common,classpath:/db/migration/mysql
